UPR:
  data_file: 'gs://classification_data/UPR.csv'
  pkl_file: 'gs://classification_data/UPR.pkl'
  label_col: 'Issue'
  text_col: 'Recommendation'
  sep: ','

PlanInternational_themes:
  data_file: 'gs://classification_data/PlanInternational_themes.csv'
  pkl_file: 'gs://classification_data/PLAN_themes.pkl'
  label_col: 'topics'
  text_col: 'Paragraph text'
  sep: ','

PlanInternational_persons:
  data_file: 'gs://classification_data/PlanInternational_affected_persons.csv'
  pkl_file: 'gs://classification_data/PLAN_affected_persons.pkl'
  label_col: 'affected_persons'
  text_col: 'paragraph text'
  sep: ','

PlanInternational_paragraphs:
  data_file: 'gs://classification_data/PlanInternational_paragraphs.csv'
  pkl_file: 'gs://classification_data/PLAN_paragraphs.pkl'
  label_col: 'label'
  text_col: 'text'
  sep: ','

PlanInternational_themes_200:
  data_file: 'gs://classification_data/PlanInternational_themes_200.csv'
  pkl_file: 'gs://classification_data/PLAN_themes_200.pkl'
  label_col: 'label'
  text_col: 'text'
  sep: ','

UHRI_themes:
  data_file: 'gs://classification_data/UHRI.csv'
  pkl_file: 'gs://classification_data/UHRI_themes.pkl'
  label_col: 'themes'
  text_col: 'text'
  sep: '$'

UHRI_affected_persons:
  data_file: 'gs://classification_data/UHRI.csv'
  pkl_file: 'gs://classification_data/UHRI_affected_persons.pkl'
  label_col: 'affected_persons'
  text_col: 'text'
  sep: '$'

UHRI_sdgs:
  data_file: 'gs://classification_data/UHRI.csv'
  pkl_file: 'gs://classification_data/UHRI_sdgs.pkl'
  label_col: 'sdgs'
  text_col: 'text'
  sep: '$'
